{"name": "insights.specs.Specs.nova_compute_log", "exec_time": 4.172325134277344e-05, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/newest.egg/insights/core/plugins.py\", line 101, in invoke\n    return self.component(broker)\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 870, in __call__\n    raise ContentException(\"None of [%s] found.\" % ', '.join(self.paths))\ninsights.core.exceptions.ContentException: None of [/var/log/containers/nova/nova-compute.log, /var/log/nova/nova-compute.log] found.\n"], "results": null, "ser_time": 7.867813110351562e-06}