{"name": "insights.specs.Specs.tomcat_vdc_fallback", "exec_time": 9.560585021972656e-05, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 102, in call_serializer\n    return func(value), None\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 87, in serialize\n    \"object\": to_dict(obj, root=root),\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 1564, in serialize_command_output\n    rc = obj.write(dst)\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 143, in write\n    content = \"\\n\".join(self._clean_content())\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 85, in _clean_content\n    content = self.content  # load first for debugging info order\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 136, in content\n    raise ContentException(\"Empty (after filtering): %s\" % self.path)\ninsights.core.exceptions.ContentException: Empty (after filtering): insights_commands/find_.usr.share_-maxdepth_1_-name_tomcat_-exec_.bin.grep_-R_-s_VirtualDirContext_--include_.xml\n"], "results": null, "ser_time": 0.013114452362060547}