{"name": "insights.specs.Specs.satellite_custom_ca_chain", "exec_time": 5.2928924560546875e-05, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 102, in call_serializer\n    return func(value), None\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 87, in serialize\n    \"object\": to_dict(obj, root=root),\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 1564, in serialize_command_output\n    rc = obj.write(dst)\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 143, in write\n    content = \"\\n\".join(self._clean_content())\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 85, in _clean_content\n    content = self.content  # load first for debugging info order\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 127, in content\n    self._content = self.load()\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 411, in load\n    raw = self.ctx.shell_out(\n  File \"/var/lib/insights/newest.egg/insights/core/context.py\", line 194, in shell_out\n    raw = self.check_output(cmd, timeout=timeout, keep_rc=keep_rc, env=env, signum=signum)\n  File \"/var/lib/insights/newest.egg/insights/core/context.py\", line 188, in check_output\n    return subproc.call(cmd, timeout=timeout or self.timeout, signum=signum,\n  File \"/var/lib/insights/newest.egg/insights/util/subproc.py\", line 181, in call\n    res = p(keep_rc=keep_rc)\n  File \"/var/lib/insights/newest.egg/insights/util/subproc.py\", line 92, in __call__\n    raise CalledProcessError(rc, self.cmds[0], output)\ninsights.core.exceptions.CalledProcessError: (2, ['timeout', '-s', '9', '120', '/usr/bin/awk', 'BEGIN { pipe=\"openssl x509 -noout -subject -enddate\"} /^-+BEGIN CERT/,/^-+END CERT/ { print | pipe } /^-+END CERT/ { close(pipe); printf(\"\\\\n\")}', '/etc/pki/katello/certs/katello-server-ca.crt'], b\"awk: cmd. line:1: fatal: cannot open file `/etc/pki/katello/certs/katello-server-ca.crt' for reading: No such file or directory\\n\")\n"], "results": null, "ser_time": 0.005679130554199219}