{"name": "insights.specs.Specs.httpd_limits", "exec_time": 0.00013494491577148438, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/newest.egg/insights/core/plugins.py\", line 101, in invoke\n    return self.component(broker)\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 1267, in __call__\n    source = source.content\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 127, in content\n    self._content = self.load()\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 411, in load\n    raw = self.ctx.shell_out(\n  File \"/var/lib/insights/newest.egg/insights/core/context.py\", line 194, in shell_out\n    raw = self.check_output(cmd, timeout=timeout, keep_rc=keep_rc, env=env, signum=signum)\n  File \"/var/lib/insights/newest.egg/insights/core/context.py\", line 188, in check_output\n    return subproc.call(cmd, timeout=timeout or self.timeout, signum=signum,\n  File \"/var/lib/insights/newest.egg/insights/util/subproc.py\", line 181, in call\n    res = p(keep_rc=keep_rc)\n  File \"/var/lib/insights/newest.egg/insights/util/subproc.py\", line 92, in __call__\n    raise CalledProcessError(rc, self.cmds[0], output)\ninsights.core.exceptions.CalledProcessError: (1, ['timeout', '-s', '9', '120', '/usr/bin/pgrep', '-o', 'httpd'], b'')\n"], "results": null, "ser_time": 1.7881393432617188e-05}